### ISSUE TITLE
Package installation fails on Windows 10

### ISSUE THREAD

**Issue by mgcollie** [CesiumGS/cesium-unity-samples#32] opened 2022-12-14 14:48 UTC
I'm getting the following error when trying to install this on Windows 10 

error CS0016: Could not write to output file 'C:\Users\runneradmin\AppData\Local\Temp\09094c8b-c05b-4ac9-ba57-e1c9f8000f72\generated\Runtime\Unity.SourceGenerators\Unity.MonoScriptGenerator.MonoScriptInfoGenerator\AssemblyMonoScriptTypes.gen.cs' -- 'Could not find a part of the path 'C:\Users\runneradmin\AppData\Local\Temp\09094c8b-c05b-4ac9-ba57-e1c9f8000f72\generated\Runtime\Unity.SourceGenerators\Unity.MonoScriptGenerator.MonoScriptInfoGenerator\AssemblyMonoScriptTypes.gen.cs'.'

**Comment by mgcollie** [comment] 2022-12-14 18:35
I think this issue is a duplicate of this one:  https://github.com/CesiumGS/cesium-unity/issues/156

**Comment by kring** [comment] 2022-12-15 01:26
Yes, I think you're right. Do you mind downloading https://github.com/CesiumGS/cesium-unity/suites/9829949633/artifacts/473549825, extracting the .tgz, installing it with the Unity Package Manager, and seeing if that fixes the problem?

**Comment by mgcollie** [comment] 2022-12-15 04:58
sure thing. trying now. stay tuned.

**Comment by mgcollie** [comment] 2022-12-15 13:19
That worked. Thank you.

**Comment by kring** [comment] 2022-12-19 10:48
Thanks for trying it @mgcollie. I'm going to close this issue as a duplicate of https://github.com/CesiumGS/cesium-unity/issues/156.

**Closed by kring** 2022-12-19 10:48 UTC
