### ISSUE TITLE
Support for pre-existing projects

### ISSUE THREAD

**Issue by brandondsantos** [CesiumGS/cesium-unity-samples#30] opened 2022-12-09 01:08 UTC
Hi, there! I've been using the platform ever since Cesium for Unreal was launched and even had a Cesium blog article written about a game I'm developing. I just want to ask if there's a more convenient way to download Cesium for Unity (with the samples or URP support)? I simply just want to add Cesium to my already-existing project and work with it from there. A few suggestions I have for doing this would be 

1. Add Cesium for Unity as an Editor Extension on the Unity Asset Store.
2. Export Cesium for Unity as a .unitypackage (Right-click in the Editor and click on Export Package)

I don't know if Cesium is already in the process of doing this, or isn't all that familiar with the software, but I hope these suggestions help for you either way! I look forward in seeing where this plugin goes.

Sincerely,
B. Santos, DBA Radiointeractive
Developer, _[Three Mile Island](https://cesium.com/blog/2022/06/09/three-mile-island-cesium-for-unreal/)_

**Comment by kring** [comment] 2022-12-09 07:56
@brandondsantos we can't publish to the Asset Store due to some apparently unreasonable terms. But the scoped package registry approach should be nearly as easy as a .unitypackage. Have you tried it out and found it difficult or otherwise less than ideal? I'm not sure we've done a great job advertising it, but instructions are here:
https://cesium.com/learn/unity/unity-quickstart/#step-1-create-a-new-project-and-import-the-cesium-for-unity-package

You can also simple download the .tgz from the [releases page](https://github.com/CesiumGS/cesium-unity/releases) and import that using the Unity Package Manager.

**Comment by jolly17ify** [comment] 2022-12-11 11:12
Hi kring
I wanted to setup in a pre-existing project and not in a new one(for which you have given instructions). I made a package using your sample project and imported it in my project but in that even the sample scene is not rendering.

**Comment by kring** [comment] 2022-12-12 00:19
@jolly17ify the instructions above will work for that too. Just skip the part where you create a new project, and instead set up the scoped registry in your existing one. It should work much better than creating your own package from the samples project and then importing that. One thing you need to watch out for, though - no matter how you install Cesium for Unity - is that Cesium for Unity does _not_ support the built-in render pipeline. You must use either the Universal Render Pipeline (URP) or the HD Render Pipeline (HDRP). If your project uses the built-in pipeline, you'll need to convert it (probably to URP) first.

**Comment by jolly17ify** [comment] 2022-12-24 06:29
@kring Sorry for the late reply. My Unity version is 2021.2.13f1. I followed the instructions. I even tried them on an empty project with just Cesium + latest Oculus integration SDK and setup my scene using the given instructions and default XR rig but I get the following error:
NotImplementedException: The native implementation is missing so Update cannot be invoked. This may be caused by a missing call to CreateImplementation in one of your constructors, or it may be that the entire native implementation shared library is missing or out of date.
12-24 11:55:49.170  4462  4487 E Unity   :   at CesiumForUnity.Cesium3DTileset.Update () [0x00012] in <8a2fff58459744c99fe019c44f4f40ef>:0

**Comment by jolly17ify** [comment] 2022-12-24 06:34
I can even send you the empty project, if required.

**Comment by jolly17ify** [comment] 2022-12-24 06:37
Also get this error at start:
DllNotFoundException: CesiumForUnityNative-Runtime assembly:<unknown assembly> type:<unknown type> member:(null)
12-24 12:05:09.384  5085  5186 E Unity   :   at (wrapper managed-to-native) Reinterop.ReinteropInitializer.initializeReinterop(ulong,intptr,int)
12-24 12:05:09.384  5085  5186 E Unity   :   at Reinterop.ReinteropInitializer..cctor () [0x083e6] in <8a2fff58459744c99fe019c44f4f40ef>:0 
12-24 12:05:09.384  5085  5186 E Unity   : Rethrow as TypeInitializationException: The type initializer for 'Reinterop.ReinteropInitializer' threw an exception.
12-24 12:05:09.384  5085  5186 E Unity   :   at CesiumForUnity.CesiumGeoreference.CreateImplementation () [0x00000] in <8a2fff58459744c99fe019c44f4f40ef>:0 
12-24 12:05:09.384  5085  5186 E Unity   :   at CesiumForUnity.CesiumGeoreference..ctor () [0x0004d] in <8a2fff58459744c99fe019c44f4f40ef>:0

**Comment by kring** [comment] 2022-12-28 02:30
So it's working on Windows, but fails when run on the Oculus? Perhaps you're building for ARM7 (32-bit) instead of ARM64? Cesium only works on 64-bit systems. It's an option in the Player Settings.

**Comment by j9liu** [comment] 2023-01-05 17:55
@jolly17ify Are you able to use a Unity Editor of version 2021.3.2f1 or higher? We haven't tested it with versions of Unity lower than that, so I'm not surprised it is breaking.

**Comment by kring** [comment] 2023-10-25 02:52
@hui89238rhifnsf please start a [community forum](https://community.cesium.com/c/cesium-for-unity/13) thread describing your problem in as much detail as possible. You haven't told us anything about platform or version, or even when this error occurs, and this is not really the place, anyway.

**Comment by j9liu** [comment] 2024-03-22 18:57
Closing this thread because it is old + we already provide Cesium for Unity through scoped registry, which is easier than building from source.

**Closed** 2024-03-22 18:56 UTC
